const USERINFO = 'USERINFO'
const INSTITUTE = 'INSTITUTE'
const SETNOTICATIONS = 'SETNOTIFICATIONS'
const NOTREADNOTIFICATIONS = 'NOTREADNOTIFICATIONS'

export default {}
export {
    USERINFO,
    INSTITUTE,
    SETNOTICATIONS,
    NOTREADNOTIFICATIONS
}
