const USERINFO = 'USERINFO'
const INSTITUTE = 'INSTITUTE'
const SETNOTICATIONS = 'SETNOTIFICATIONS'
const NOTREADNOTIFICATIONS = 'NOTREADNOTIFICATIONS'
const SETPRIVILEDGES = 'SETPRIVILEDGES'

export default {}
export {
    USERINFO,
    INSTITUTE,
    SETNOTICATIONS,
    NOTREADNOTIFICATIONS,
    SETPRIVILEDGES
}
